FROM oven/bun AS base
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM base AS build
COPY ./src ./src
COPY tsconfig.json ./
ENV NODE_ENV=production
RUN bun build \
    --compile \
    --minify-whitespace \
    --minify-syntax \
    --outfile worker \
    src/infrastructure/queue/WorkerRunner.ts

FROM oven/bun AS runtime
WORKDIR /app

USER bun

ENV NODE_ENV=production

# Copy the compiled binary from build stage
COPY --from=build /app/worker .

CMD ["./worker"]